// This file was generated by a program.
package mypackage

// package names to be imported

type Eod uint8

const (
	Entry Eod = iota
	Do
	Exit
)

type DebugLogger interface {
	Println(string)
}

var logger DebugLogger

func ConfigureLog(p DebugLogger) {
	logger = p
}

const (
	debug = true
)
